---
title: "Liquefaction"
---

## Dataset Reference

<table class="data-table">
  <thead>
    <tr>
      <th>Dataset</th>
      <th>Measurement</th>
      <th>Units</th>
      <th>Source</th>
      <th>Release Year</th>
      <th>Years of Data</th>
      <th>Coverage</th>
      <th>Resolution</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Global liquefaction susceptibility map </td>
      <td>---</td>
      <td>---</td>
      <td><a href="https://zenodo.org/records/2583746" target="_blank">Zenodo</a></td>
      <td>2019</td>
      <td>NA</td>
      <td>Global</td>
      <td>1.2 kilometers</td>
    </tr>
  </tbody>
</table>

---

::: {.wiki-section}
## What Is It?

One of the ways earthquakes can cause damage is through temporarily converting the ground into a liquid-like phase, in a process called soil liquefaction. Strong vibrations or increased water pressure in water-saturated sediment allow the formerly stable and static soil particles to move around and behave like a fluid. Essentially, the added energy is sufficient to convert the solid ground into a pseudo-liquid. When the ground begins acting like a liquid, it loses strength and can no longer support weight, such as buildings or bridges. Without solid foundations, the structures can collapse. The liquified earth is also able to flow down even gentle slopes, causing landslides. This map shows which parts of the city are most susceptible to soil liquefaction, and therefore which areas are more vulnerable to liquefaction-based damage should an earthquake occur. 

Liquefaction is typically discussed in relation to earthquakes, but non-seismic loads can also increase pore water pressure to the point of triggering liquefaction. Examples of non-seismic triggers include the failures of dams and mine tailings impoundments.
:::

::: {.wiki-section}
## Why Use It?

While all of a city has the same likelihood of seismic activity (given the geographic scale of earthquakes), not all areas will have the same susceptibility to liquefaction, and therefore different risks of liquefaction-based damage in the event of an earthquake. Factors such as softer soil, greater slope, and worse drainage can heighten the risk of liquefaction and the damage it can cause. Understanding which areas are more susceptible can inform response measures. 

The three general ways to reduce an area's liquefaction risk are to avoid susceptible areas, strengthen structures, and strengthen the soil. The most basic response is to decrease exposure by avoiding construction and inhabitance in liquefaction-prone areas: keep people and assets to areas that will handle earthquake activity better. It is not always possible to avoid susceptible areas, especially when they are already inhabited. In this case, it is important to engineer structures, and specifically their foundations, to be more liquefaction resistant. The most fundamental response to liquefaction susceptibility is mitigation by way of strengthening the soil. Soil conditions can be improved by various methods, including drainage, soil densification and sediment replacement. 
:::

::: {.wiki-section}
## How Is It Made?

This liquefaction susceptibility map is generated by a geospatial regression model for designed for global application by <a href="https://doi.org/10.1785/0120160198" target="_blank">Zhu et al. (2017)</a>. (The team actually developed two models: a coastal model and inland model. The liquefaction susceptibility map combines these two models, using the coastal model for regions within 20 kilometers of the sea, and the inland model for everywhere else.) The probability model was trained on the observed liquefaction of 27 earthquake events in 6 countries, including events where no liquefaction was observed, and uses proxies for soil density, soil saturation and earthquake loading as explanatory variables. As a proxy for earthquake loading the model uses peak ground velocity (PGV, the maximum ground velocity recorded during a particular seismic event), and as a proxy for soil density, the a slope-derived time-averaged shear wave velocity $V_{S30}$. $V_{S30}$ is the speed at which a shear wave (a seismic wave travelling perpendicular to the direction of propagation, and also known as a secondary or S-wave) travels from the surface to a depth of 30 meters. This variable, which is often used to quantify soil conditions, requires on the ground measurement. The model, therefore, approximates the variable using slope. For soil saturation, the model uses a number of variables: the coastal model uses precipitation, distance to water bodies, and, for the inland model, the water table depth. 

As trained, the model is a liquefaction probability model. It predicts how likely liquefaction is in an area given the empirical characteristics of an observed earthquake. While this prediction is useful for validating the model's performance, it is not useful for understanding which areas are susceptible to future liquefaction. To convert the probability model into a susceptibility model, the PGV variable (which describes the seismic activity of a particular earthquake) is simply removed from the trained model. The resulting values not individually meaningful in an absolute sense, but they can be classed to show which areas have less and greater susceptibility. In this map, the values are classed as very low, low, moderate, high and very high. 
:::

::: {.wiki-section}
## How Should We Interpret It?

This map shows areas' susceptibility to liquefaction rather than their probability of liquefaction. Whereas probability quantifies how likely an event is to occur in a certain time period (e.g., in the next 10 years or during this window), susceptibility measures how likely an event is to occur given a triggering event. One way this difference is often described is that probability includes a temporal dimension while susceptibility does not and is limited to the inherent characteristics of a place. This difference can be seen in the construction of the liquefaction susceptibility model: the model was first developed with the PGV of historical earthquakes – that is, they included a trigger event; to make it a susceptibility model that applied beyond those specific events, the PGV was removed, leaving more or less unchanging characteristics, soil density and soil saturation. 

Because the likelihood of a triggering earthquake is excluded, it is important to understand that liquefaction susceptibility may be high in areas where the probability of seismic activity is low. Similarly, areas with low liquefaction susceptibility may have high probabilities of earthquakes and could experience significant seismic damage in other ways. It is helpful, then, to view liquefaction susceptibility maps in conjunction with maps of seismic hazard. 

It is also important, when using these specific liquefaction maps, to remember that they were developed using globally available data. The tradeoff of this choice, which made susceptibility maps available to far more areas, is that the maps take into account less site-specific data than an on the ground assessment would. For example, the time-averaged shear wave velocity $V_{S30}$, which is used to quantify soil density, is calculated using slope rather than in situ testing. This means that areas sharing similar slope characteristics but having different compositions (sand, rock, etc.) have the same alleged soil density in this model. While the model performs quite well, on the ground analysis could give a more localized picture of susceptibility. Similarly, the resolution of the model is quite low, at a 1.2-kilometer grid size. Liquefaction susceptibility may vary significantly within these grid cells, depending on the composition of the soil. 
:::

::: {.wiki-section}
## Source Data Citation

<div class="citation-block">
Zorn, Conrad, and Elco Koks. 2019. “Global Liquefaction Susceptibility Map.” Zenodo. https://doi.org/10.5281/ZENODO.2583746.
</div>
:::
