---
title: "Seismic Hazard"
---

## Dataset Reference

<table class="data-table">
  <thead>
    <tr>
      <th>Dataset</th>
      <th>Measurement</th>
      <th>Units</th>
      <th>Source</th>
      <th>Release Year</th>
      <th>Years of Data</th>
      <th>Coverage</th>
      <th>Resolution</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Global Earthquake Model (GEM) Seismic Hazard Map </td>
      <td>---</td>
      <td>---</td>
      <td><a href="https://maps.openquake.org/map/global-seismic-hazard-map/" target="_blank">Gobal Earthquake Model</a></td>
      <td>2023</td>
      <td>NA</td>
      <td>Global</td>
      <td>1 kilometer</td>
    </tr>
  </tbody>
</table>

Note that we are now using the 2023 version as opposed to the 2018 version so we need to update the resolution and maybe other aspects 
---

::: {.wiki-section}
## Methodology

This map depicts the geographic distribution of the Peak Ground Acceleration (PGA) with a 10% probability of being exceeded in 50 years, computed for reference rock conditions (shear wave velocity of 760-800 m/s). Seismic risk in cities has increased mainly due to urbanization, poor land-use planning and construction, inadequate infrastructure and services, and environmental degradation. Urban risk predictions and expected losses from major earthquakes in the future justify proactive risk mitigation activities. 

These data and map are derived from the Global Earthquake Model, which provides information on probabilistic earthquake risk; at its scale, it does not address the vulnerability to earthquakes of individual structures or sub-regions. An earthquake with moderate damage potential can cause structural damage to unreinforced masonry buildings and the movement of wood-frame houses. See <a href="https://web.archive.org/web/20120306024658/http://quake.abag.ca.gov/shaking/mmi/plaintext/" target="_blank">here</a> for more. 
:::

::: {.wiki-section}
## Source Data Citation

<div class="citation-block">
Pagani, Marco, Julio García-Pelaez, Robin Gee, Kendra Johnson, Valerio Poggi, Michele Simionato, Richard Styron, et al. 2018. “GEM Global Seismic Hazard Map v.2023.1.” https://doi.org/10.13117/GEM-GLOBAL-SEISMIC-HAZARD-MAP-2018.1.
</div>
:::
