---
title: "Forest & Deforestation"
---

## Dataset Reference

<table class="data-table">
  <thead>
    <tr>
      <th>Dataset</th>
      <th>Measurement</th>
      <th>Units</th>
      <th>Source</th>
      <th>Release Year</th>
      <th>Years of Data</th>
      <th>Coverage</th>
      <th>Resolution</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Hansen et al., Global Forest Change </td>
      <td>---</td>
      <td>---</td>
      <td><a href="https://glad.earthengine.app/view/global-forest-change?#bl=off;old=off;dl=1;lon=20;lat=10;zoom=3;" target="_blank">University of Maryland</a></td>
      <td>NA</td>
      <td>2000–2023</td>
      <td>Global</td>
      <td>1 arc second (30 meters)</td>
    </tr>
  </tbody>
</table>

---

::: {.wiki-section}
## What Is It?

Due to human activity and natural processes (as well as their combination), forest cover is always changing. Over the period of 2000–2012, 2.3 million square kilometers of forest were lost globally, while 0.8 million were gained, resulting in a net loss of 1.5 million square kilometers. This map shows both which areas are forested, and where there has been forest loss since 2000. Forested areas are 30 meter by 30 meter areas with at least 20% tree cover, as assessed from satellite imagery. 
:::

::: {.wiki-section}
## Why Use It?

On a global scale, forests are vitally important to the mitigation of anthropogenic climate change by removing CO<sub>2</sub> from the atmosphere. They also have important roles at the local level. Among these effects are local climate, flood and landslide prevention, biodiversity and animal habitat, water and air purification, and resource provision. 

Trees draw water from deep underground and pump it to the surface. This water then evaporates from their leaves in a process called evapotranspiration. The release of water increases humidity and causes local cooling. The added moisture can then form rain clouds which both reflect sun light (increased albedo), causing further cooling, and water other plants in the surrounding area with shallower root systems. Tree roots also reduce the risk of floods and landslides, by slowing run off, strengthening soil, absorbing water, and accelerating evaporation. As it slows down the water, it also filters it, making it cleaner for drinking. Above ground, trees also act as filters, catching particulate matter on their surfaces. 

To reduce global climate change and local heat, to lessen the risk of flooding and landslides, and to maintain ecological diversity, among other reasons, it is important to prevent the loss of forests. Forests are threatened by both human activity, such as deforestation for reasons of agriculture, urban expansion, and timber, and by natural processes which are often accentuated by human activity, such as wildfire and insect epidemics. 
:::

::: {.wiki-section}
## How Is It Made?

For this dataset, areas of vegetation were first detected using red and infrared bands from the Landsat 7 satellite. These vegetated areas were then filtered by height, with vegetation taller than 5 meters classified as tree cover. If a 30 meter by 3- meter pixel has at least 20% tree cover, it is classified as forest. The dataset begins with a base model of forest coverage in the year 2000, and then measures forest loss for 2000–2023 and forest gain for 2000–2012. 
:::

::: {.wiki-section}
## How Should We Interpret It?

As with all global remote sensing data, this dataset is not specific to local conditions or ecosystems. It may be more or less accurate with different forest types. <a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC9258877/?" target="_blank">One study</a> has found that this global forest change dataset may overestimate deforestation in the Amazon Basin.
:::

::: {.wiki-section}
## Source Data Citation

<div class="citation-block">
Hansen, M. C., P. V. Potapov, R. Moore, M. Hancher, S. A. Turubanova, A. Tyukavina, D. Thau, et al. 2013. “High-Resolution Global Maps of 21st-Century Forest Cover Change.” Science 342 (6160): 850–53. https://doi.org/10.1126/science.1244693.
</div>
:::
