---
title: "Built-Up Area"
---

## Dataset Reference

<table class="data-table">
  <thead>
    <tr>
      <th>Dataset</th>
      <th>Measurement</th>
      <th>Units</th>
      <th>Source</th>
      <th>Release Year</th>
      <th>Years of Data</th>
      <th>Coverage</th>
      <th>Resolution</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>World Settlement Footprint Evolution</td>
      <td>---</td>
      <td>---</td>
      <td><a href="https://download.geoservice.dlr.de/WSF_EVO/files/?" target="_blank">German Aerospace Center</a></td>
      <td>2021</td>
      <td>1985–2015</td>
      <td>Global</td>
      <td>30 meters</td>
    </tr>
  </tbody>
</table>

---

::: {.wiki-section}
## What Is It?

Built-up area refers to the spatial extent distribution of land occupied by man-made structures such as residential, commercial, and industrial buildings, roads, parks, and other pervious surfaces within the city boundaries. This map identifies when and where these changes occurred, offering a historical view of how urban sprawl has evolved over time. 
:::

::: {.wiki-section}
## Why Use It?

Understanding the spatial footprint of urbanized areas is essential for planning the provision of public services and infrastructure. Also, understanding when the land was urbanized contextualizes the age of buildings—particularly when analyzed alongside layers on heritage sites or constructions— and infrastructure in a given area, which can have implications for the structural integrity and resilience to hazards. 
:::

::: {.wiki-section}
## How Is It Made?

The World Settlement Footprint developed the WSF Evolution data set to map urban change between 1985 to 2015. Because existing global layers provide limited time steps and poor quality, WSF developed an iterative approach using past settlement extents using Landsat data, available from 1985 at a 30-meter resolution. Using various measures and spectral indices, WSF iteratively generated settlement and non-settlement training data to create a machine learning model to predict when settlements expanded.
:::

::: {.wiki-section}
## How Should We Interpret It?

The map displays when land was urbanized in 5-year ranges, which provides insight as to the spatial-temporal patterns of urban change. However, several caveats should be considered when interpreting this data. First, the WSF does not account for land that transitioned from urbanized to non-urbanized -- a relatively rare but possible phenomenon. Second, any area that was already built up before 1985 is not captured in the dataset. This is particularly relevant because in some cities there may be substantial differences between settlements developed shortly before 1985 and those established decades earlier. Finally, areas can also be redeveloped, which may affect the overall accuracy of the temporal measure of urbanization.

While the year an area was urbanized can offer clues about the age of buildings and infrastructure, it’s not always a reliable proxy for structural vulnerability. For instance, many countries adopted anti-seismic building codes before 1985, and many older buildings have since been retrofitted, replaced, or demolished. For more accurate assessments of risk or building conditions, this layer should be used alongside other datasets, such as those identifying heritage sites or protected structures. 
:::

::: {.wiki-section}
## Source Data Citation

<div class="citation-block">
Marconcini, Mattia, Annekatrin Metz- Marconcini, Thomas Esch, and Noel Gorelick. 2021. “Understanding Current Trends in Global Urbanisation - The World Settlement Footprint Suite.” GI_Forum 2021, Volume 9, (June): 33–38. https://doi.org/10.1553/giscience2021_01_s33. 
</div>
:::
